[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[theme]
base = "dark"
primaryColor = "#0ecb81"
backgroundColor = "#0b0e11"
secondaryBackgroundColor = "#161b22"
textColor = "#ffffff"

[server]
headless = true
